<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Jellyfin.Plugin.PersonalRatings</AssemblyName>
    <RootNamespace>Jellyfin.Plugin.PersonalRatings</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.10.7">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="10.10.7">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Configuration\configPage.html" />
    <None Remove="Web\details-rating.js" />
    <None Remove="Web\manage-page.css" />
    <None Remove="Web\manage-page.html" />
    <None Remove="Web\manage-page.js" />
    <EmbeddedResource Include="Configuration\configPage.html" />
    <EmbeddedResource Include="Web\details-rating.js" />
    <EmbeddedResource Include="Web\manage-page.css" />
    <EmbeddedResource Include="Web\manage-page.html" />
    <EmbeddedResource Include="Web\manage-page.js" />
  </ItemGroup>

</Project>
